/********************************************************************
* deedict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error deedict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledeedict();
extern void G__cpp_setup_inheritancedeedict();
extern void G__cpp_setup_typetabledeedict();
extern void G__cpp_setup_memvardeedict();
extern void G__cpp_setup_globaldeedict();
extern void G__cpp_setup_memfuncdeedict();
extern void G__cpp_setup_funcdeedict();
extern void G__set_cpp_environmentdeedict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MDEEFrame.h"
#include "MTree.h"
#include "MFitParam.h"
#include "MGraphFrame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__deedictLN_TClass;
extern G__linked_taginfo G__deedictLN_TBuffer;
extern G__linked_taginfo G__deedictLN_TMemberInspector;
extern G__linked_taginfo G__deedictLN_TObject;
extern G__linked_taginfo G__deedictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__deedictLN_string;
extern G__linked_taginfo G__deedictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__deedictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__deedictLN_TList;
extern G__linked_taginfo G__deedictLN_TTimer;
extern G__linked_taginfo G__deedictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__deedictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__deedictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__deedictLN_TFile;
extern G__linked_taginfo G__deedictLN_TCanvas;
extern G__linked_taginfo G__deedictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__deedictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__deedictLN_TQObject;
extern G__linked_taginfo G__deedictLN_TGWindow;
extern G__linked_taginfo G__deedictLN_TGObject;
extern G__linked_taginfo G__deedictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__deedictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__deedictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__deedictLN_TGFrame;
extern G__linked_taginfo G__deedictLN_TGCompositeFrame;
extern G__linked_taginfo G__deedictLN_TGLayoutHints;
extern G__linked_taginfo G__deedictLN_TGTextButton;
extern G__linked_taginfo G__deedictLN_TGMainFrame;
extern G__linked_taginfo G__deedictLN_TGTransientFrame;
extern G__linked_taginfo G__deedictLN_TGPopupMenu;
extern G__linked_taginfo G__deedictLN_TGMenuBar;
extern G__linked_taginfo G__deedictLN_TGTextBuffer;
extern G__linked_taginfo G__deedictLN_TGTextEntry;
extern G__linked_taginfo G__deedictLN_TGComboBox;
extern G__linked_taginfo G__deedictLN_TGPictureButton;
extern G__linked_taginfo G__deedictLN_TGFileInfo;
extern G__linked_taginfo G__deedictLN_TGLabel;
extern G__linked_taginfo G__deedictLN_TGNumberEntry;
extern G__linked_taginfo G__deedictLN_TGHProgressBar;
extern G__linked_taginfo G__deedictLN_TGStatusBar;
extern G__linked_taginfo G__deedictLN_TTree;
extern G__linked_taginfo G__deedictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__deedictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__deedictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__deedictLN_TH1F;
extern G__linked_taginfo G__deedictLN_TGraph;
extern G__linked_taginfo G__deedictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__deedictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__deedictLN_TMinuit;
extern G__linked_taginfo G__deedictLN_efitkind;
extern G__linked_taginfo G__deedictLN_ecalcmass;
extern G__linked_taginfo G__deedictLN_MEpax;
extern G__linked_taginfo G__deedictLN_MIdent;
extern G__linked_taginfo G__deedictLN_MTree;
extern G__linked_taginfo G__deedictLN_MFitParam;
extern G__linked_taginfo G__deedictLN_MPart;
extern G__linked_taginfo G__deedictLN_MDEEFrame;
extern G__linked_taginfo G__deedictLN_vectorlEMPartcOallocatorlEMPartgRsPgR;
extern G__linked_taginfo G__deedictLN_reverse_iteratorlEvectorlEMPartcOallocatorlEMPartgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__deedictLN_TGHSlider;
extern G__linked_taginfo G__deedictLN_MGraphFrame;
extern G__linked_taginfo G__deedictLN_MInfo;

/* STUB derived class for protected member access */
